"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sdpk7_*zsl7_)p+46j25x29#yk$n)e@m61v50^f+fakrrq95wt'

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False in production for security
# In production, set this via environment variable: DEBUG = os.getenv('DEBUG', 'False') == 'True'
DEBUG = True

ALLOWED_HOSTS = []
# In production, set this to your domain: ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection enabled
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bookshelf.middleware.CSPMiddleware',  # Custom CSP middleware for XSS protection
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Authentication settings
LOGIN_REDIRECT_URL = 'relationship_app:book-list'

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Media files (for user uploads like profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# SECURITY SETTINGS
# ============================================================================
# These settings enhance application security by protecting against common
# vulnerabilities like XSS, CSRF, and clickjacking attacks.

# XSS Protection: Enable browser's XSS filter
# This header tells browsers to enable their built-in XSS protection
SECURE_BROWSER_XSS_FILTER = True

# Content Type Protection: Prevent MIME type sniffing
# Prevents browsers from trying to guess content types, reducing XSS risks
SECURE_CONTENT_TYPE_NOSNIFF = True

# Frame Options: Prevent clickjacking attacks
# Options: 'DENY' (no framing), 'SAMEORIGIN' (same origin only), or None
X_FRAME_OPTIONS = 'DENY'

# Cookie Security Settings
# In production with HTTPS, set these to True to ensure cookies are only
# sent over secure connections
# Note: Set to False in development if not using HTTPS
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# CSRF Cookie Settings
CSRF_COOKIE_HTTPONLY = True  # Prevents JavaScript access to CSRF cookie
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to session cookie

# Content Security Policy (CSP)
# CSP helps prevent XSS attacks by specifying which domains can load resources
# This is a basic CSP - adjust based on your application's needs
# For production, use django-csp package for more advanced CSP configuration
SECURE_CSP_DEFAULT_SRC = "'self'"
SECURE_CSP_SCRIPT_SRC = "'self'"
SECURE_CSP_STYLE_SRC = "'self' 'unsafe-inline'"  # 'unsafe-inline' needed for Django admin
SECURE_CSP_IMG_SRC = "'self' data:"
SECURE_CSP_FONT_SRC = "'self'"

# Additional Security Headers
# HSTS (HTTP Strict Transport Security) - only enable in production with HTTPS
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# SSL Redirect - only enable in production
# SECURE_SSL_REDIRECT = True
